// src/app/layout.tsx
import './globals.css';
import { Roboto } from 'next/font/google';

// Google Fonts (Roboto) 적용
const roboto = Roboto({
  subsets: ['latin'], // 지원되는 언어 서브셋
  weight: ['400', '700'], // 가중치 선택
  display: 'swap', // Fallback 폰트 사용 시 렌더링 방식을 지정
});

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

